In [1]:
import pandas as pd
import numpy as np

# Text processing
from sklearn.feature_extraction.text import TfidfVectorizer

# Model selection
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Models
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
# Load CSV
df = pd.read_csv("text_classification.csv")

# View dataset
df.head()

                                             text     label
0          I love this product it works perfectly  positive
1            This movie was amazing and inspiring  positive
2  The customer service was excellent and helpful  positive
3                I am very happy with the results  positive
4      The experience was fantastic and enjoyable  positive

In [4]:
# Check dataset info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    20 non-null     str
 1   label   20 non-null     str
dtypes: str(2)
memory usage: 1.3 KB

In [5]:
# Check label distribution
df['label'].value_counts()

label
neutral     10
positive     5
negative     5
Name: count, dtype: int64

In [6]:
X = df['text']
y = df['label']

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

X_vectorized = vectorizer.fit_transform(X)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
dt_model = DecisionTreeClassifier(
    max_depth=20,
    random_state=42
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

In [9]:
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

In [10]:
results = pd.DataFrame({
    "Model": ["Decision Tree", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_dt),
        accuracy_score(y_test, y_pred_rf)
    ]
})

results

           Model  Accuracy
0  Decision Tree       0.5
1  Random Forest       0.5